using System.Text;
using System.Text.Json;
using Xunit;

namespace Argon2id.PasswordHasher.Tests;

/// <summary>
/// Data-driven known-answer tests over the vendored vector corpus at
/// <c>TestData/argon2id-vectors.json</c>. Every vector in the corpus is
/// externally sourced (RFC 9106, the Argon2 reference C implementation,
/// other ecosystems' emitted PHC strings) — none were generated by this
/// repository's own engine — so the corpus detects any divergence between
/// the pinned Konscious implementation and the rest of the Argon2 world.
/// </summary>
public class KatCorpusTests
{
    private static JsonDocument LoadCorpus()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "TestData", "argon2id-vectors.json");
        return JsonDocument.Parse(File.ReadAllBytes(path));
    }

    private static byte[] GetBytes(JsonElement vector, string baseName)
    {
        if (vector.TryGetProperty(baseName + "Hex", out JsonElement hex))
        {
            return Convert.FromHexString(hex.GetString()!);
        }

        return Encoding.UTF8.GetBytes(vector.GetProperty(baseName + "Utf8").GetString()!);
    }

    private static byte[]? GetOptionalBytes(JsonElement vector, string hexName) =>
        vector.TryGetProperty(hexName, out JsonElement hex)
            ? Convert.FromHexString(hex.GetString()!)
            : null;

    [Fact]
    public void EveryTagVector_MatchesEngineOutput()
    {
        using JsonDocument corpus = LoadCorpus();
        int checked_ = 0;

        foreach (JsonElement vector in corpus.RootElement.GetProperty("tagVectors").EnumerateArray())
        {
            string id = vector.GetProperty("id").GetString()!;
            byte[] password = GetBytes(vector, "password");
            byte[] salt = GetBytes(vector, "salt");
            byte[]? secret = GetOptionalBytes(vector, "secretHex");
            byte[]? associatedData = GetOptionalBytes(vector, "associatedDataHex");

            using var argon2 = new Konscious.Security.Cryptography.Argon2id(password)
            {
                Salt = salt,
                MemorySize = vector.GetProperty("memoryKib").GetInt32(),
                Iterations = vector.GetProperty("iterations").GetInt32(),
                DegreeOfParallelism = vector.GetProperty("parallelism").GetInt32(),
            };

            if (secret is not null)
            {
                argon2.KnownSecret = secret;
            }

            if (associatedData is not null)
            {
                argon2.AssociatedData = associatedData;
            }

            byte[] tag = argon2.GetBytes(vector.GetProperty("tagLength").GetInt32());

            Assert.True(
                string.Equals(vector.GetProperty("tagHex").GetString(), Convert.ToHexString(tag), StringComparison.OrdinalIgnoreCase),
                $"Vector '{id}' diverged: expected {vector.GetProperty("tagHex").GetString()}, engine produced {Convert.ToHexString(tag)}.");
            checked_++;
        }

        Assert.True(checked_ >= 2, "Corpus unexpectedly small — vectors file not deployed?");
    }

    [Fact]
    public void TagVectorsWithoutSecret_VerifyThroughPublicApi()
    {
        using JsonDocument corpus = LoadCorpus();
        var hasher = new Argon2idPasswordHasher(new Argon2idOptions
        {
            MemorySizeKib = 8192,
            Iterations = 1,
            DegreeOfParallelism = 1,
        });

        foreach (JsonElement vector in corpus.RootElement.GetProperty("tagVectors").EnumerateArray())
        {
            if (vector.TryGetProperty("secretHex", out _) || vector.TryGetProperty("associatedDataHex", out _))
            {
                continue; // the library intentionally exposes neither field
            }

            if (!vector.TryGetProperty("passwordUtf8", out JsonElement passwordElement))
            {
                continue; // public API takes textual passwords
            }

            string password = passwordElement.GetString()!;
            byte[] salt = GetBytes(vector, "salt");
            byte[] tag = Convert.FromHexString(vector.GetProperty("tagHex").GetString()!);

            string phc =
                "$argon2id$v=19$"
                + $"m={vector.GetProperty("memoryKib").GetInt32()}"
                + $",t={vector.GetProperty("iterations").GetInt32()}"
                + $",p={vector.GetProperty("parallelism").GetInt32()}$"
                + Convert.ToBase64String(salt).TrimEnd('=') + "$"
                + Convert.ToBase64String(tag).TrimEnd('=');

            string id = vector.GetProperty("id").GetString()!;
            Assert.True(hasher.VerifyPassword(password, phc), $"Vector '{id}' failed public-API verification. PHC: {phc}");
            Assert.False(hasher.VerifyPassword(password + "-wrong", phc), $"Vector '{id}' accepted a wrong password.");
        }
    }

    [Fact]
    public void EveryPhcStringVector_VerifiesThroughPublicApi()
    {
        using JsonDocument corpus = LoadCorpus();
        var hasher = new Argon2idPasswordHasher(new Argon2idOptions
        {
            MemorySizeKib = 8192,
            Iterations = 1,
            DegreeOfParallelism = 1,
        });

        foreach (JsonElement vector in corpus.RootElement.GetProperty("phcStringVectors").EnumerateArray())
        {
            string id = vector.GetProperty("id").GetString()!;
            string password = vector.GetProperty("password").GetString()!;
            string phc = vector.GetProperty("phc").GetString()!;

            Assert.True(hasher.VerifyPassword(password, phc), $"PHC vector '{id}' failed verification. PHC: {phc}");
            Assert.False(hasher.VerifyPassword(password + "-wrong", phc), $"PHC vector '{id}' accepted a wrong password.");
        }
    }
}
